name: 'Notify Discord on New PR (with Thread)'

on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  call_discord_notification:
    if: github.event.pull_request.draft == false
    uses: centdix/windmill-test/.github/workflows/usable-pr-opened.yml@main # TODO: change
    with:
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
